#!/usr/bin/env ruby

require 'test/unit'
require './IPyRubyData'

someRubyCode = <<END_CODE
require 'pp'

puts 'Hello TestEvalRubyString1'
a =  'Hello TestEvalRubyString2'
MakeTextData(a)
END_CODE

###############################################################
# Start by mocking the IPyKernelData code used by Convert2Data


def IPyKernelData_New(aDataValue)
  puts "--------------IPyKernelData::new---------------------"
  pp aDataValue
  puts "-----------------------------------------------------"
  return 1
end

def IPyKernelData_AddData(objId, aMIMEKey, aValue)
  puts "--------------IPyKernelData::addData-----------------"
  pp objId
  pp aMIMEKey
  pp aValue
  puts "-----------------------------------------------------"
end
  
def IPyKernelData_AppendTraceback(objId, aValue)
  puts "--------------IPyKernelData::AppendTraceback---------"
  pp objId
  pp aValue
  puts "-----------------------------------------------------"
end

def IPyKernelData_AddMetadata(objId, aMIMEKey, aMetaKey, aMetaValue)
  puts "--------------IPyKernelData::addMetadata-------------"
  pp objId
  pp aMIMEKey
  pp aMetaKey
  pp aMetaValue
  puts "-----------------------------------------------------"
end

system("reset")
puts "-------------------------------------------------------"
IPyRubyEval(someRubyCode)
puts "-------------------------------------------------------"
